apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: public.ecr.aws/l4v6k6q7/0bf0de84c3c818462fb872e32cd1471e_auth:latest
        ports:
        - containerPort: 80
        env:
        - name: AUTH_DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url
        - name: JWT_HMAC_KEY
          valueFrom: 
            secretKeyRef:
              name: auth-hmac-key
              key: hmac_key